# Welcome to Jekyll!
#
# 此配置文件用于影响整个博客的设置，只需要设置一次，之后很少需要编辑。
# 由于技术原因，当您使用'jekyll serve'时，该文件*不*自动重新加载。
# 如果您更改了该文件，请重新启动服务器进程。

# 网站设置
# 标题
title: ChenPeiming
# 位置
location: 广东，广州
# 所在公司
company: CSDN
# 公司网站
company_url: https://blog.csdn.net/cpm011023
# Github 名称
name: ChenPeiming52001
# Github
github_url: https://github.com/ChenPeiming52001
# 描述
description: 这是ChenPeiming的个人博客
# 图标 可以自定义你想要的图标
favicon: favicon.png # Image必须在assets/images中

url: https://chenpeiming52001.github.io # 站点的基本主机名和协议

## Gem
gems:
  - rouge
  - kramdown
  - jekyll-paginate
  - jekyll-geo-pattern
  - jekyll-github-metadata

plugins:
  - jekyll-paginate

# 建立设置
markdown: kramdown
excerpt_separator: "\n\n"

# kramdown 编译器设置
kramdown:
  input: GFM
  highlighter: rouge
  math_engine: mathjax
  footnote_nr: 1
  footnote_backlink: ↩

source:      .
destination: ./_site

quiet: false
defaults: []

# 分页
paginate: 10
paginate_path: 'page:num'

# 导航
navs:
  -
    href: /
    label: 主页

  -
    href: /open-source
    label: 开源项目仓库

  -
    href: /blog
    label: 博客档案

  -
    href: /bookmark
    label: 书签

  -
    href: /about
    label: 关于我

# 侧边栏 显示 受欢迎的仓库
side_bar_repo_limit: 5 # 要显示的数量

# 关于页设置
# 个人介绍
introduce: 我是一个对学习充满热情、善于思考和寻找解决方案的人。我注重细节，并且有能力在面对挑战时保持冷静和灵活应对。
# 邮箱
email: chenpeiming52001@163.com
# For about.html. 自由地创造你自己的需要显示的标签!
# 软件开发标签
skill_software_keywords: [Java,  Python]
# J2EE 开发标签
skill_j2ee_keywords: 
# 手机开发标签
skill_mobile_app_keywords: 
# Web开发标签
skill_web_keywords: [HTML, CSS, JS, JQuery,SpringBoot, MySQL, MongoDB, PHP]

# LeanCloud评论设置
valine:
  appId: GQHKkm0dcsXF5pG93TdOlrIR-gzGzoHsz
  appKey: rIP8P4hi1yd0Kva2xYvRDOs4
  # 评论框占位提示符
  placeholder: ヾﾉ≧∀≦)o快来评论一下吧!
  # 每一页最大的评论数量
  pageSize: 15
  # 设置 Gravatar 头像展示方式
  # 头像类型
  # 空字符串'' Gravatar官方图形、 mp 神秘人(一个灰白头像)、 identicon 抽象几何图形、  
  # monsterid 小怪物、 wavatar 用不同面孔和背景组合生成的头像、 retro 八位像素复古头像、
  # robohash 一种具有不同颜色、面部等的机器人、 hide 不显示头像
  avatar: 'wavatar'
  # 设置评论者标签
  tagMeta:
    Blogger: '博主'
    friends: '小伙伴'
    visitor: '访客'
  # MD5 加密后的博主邮箱 MD5加密工具：https://c.runoob.com/front-end/703/
  master: ['33c0f3680c72dd299d9463a496cc7640']
  # md5MD5 加密后的小伙伴邮箱
  friends: ['f652e9c510f5948f083d453a189b13bc', '261225df065b70eafdef4c88eecdb55d']
  # 昵称框 自动获取QQ头像 默认 false/true
  enableQQ: 'true' 
  # 每次访问强制拉取最新的评论列表头像
  avatarForce: 'true' 
